name: hazardous-mdv-edge

services:
  etl-pipeline:
    build: edge-etl-pipeline
    container_name: hmdv-etl-pipeline
    volumes:
      - ./edge-database:/app/edge-database
  api:
    build: edge-api
    container_name: hmdv-api
    ports:
      - 8000:8000
    volumes:
      - ./edge-database:/app/edge-database
    depends_on:
      - etl-pipeline
  monitoring:
    build: edge-monitoring
    container_name: hmdv-monitoring
    depends_on:
      - etl-pipeline
  webapp:
    build: edge-web-application
    container_name: hmdv-web-application
    ports:
      - 80:80
    depends_on:
      - api
