name: hmdv-edge-server

services:
  api:
    build: edge-api
    container_name: hmdv-srv-api
    volumes:
      - ./database-edge:/app/database-edge
    ports:
      - 8000:8000
  etl:
    build: edge-etl
    container_name: hmdv-srv-etl
    environment:
      API_URL: http://api:8000
      DEBUG_MODE: true
    depends_on:
      - api
  mon:
    build: edge-mon
    container_name: hmdv-srv-mon
    environment:
      API_URL: http://api:8000
      DEBUG_MODE: true
    depends_on:
      - api
  web:
    build: edge-web
    container_name: hmdv-srv-web
    ports:
      - 80:80
    depends_on:
      - api
