name: hmdv-edge-server

services:
  etl:
    build: edge-etl
    container_name: hmdv-srv-etl
    volumes:
      - ./edge-database:/app/edge-database
  api:
    build: edge-api
    container_name: hmdv-srv-api
    volumes:
      - ./edge-database:/app/edge-database
    ports:
      - 8000:8000
    depends_on:
      - etl
  mon:
    build: edge-mon
    container_name: hmdv-srv-mon
    depends_on:
      - etl
  web:
    build: edge-web
    container_name: hmdv-srv-web
    ports:
      - 80:80
    depends_on:
      - api
